---
title: "Interpretation of `tt_test()` results"
author: "Daniel Zuleta"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

```{r, error=TRUE}
# Implementation ----------------------------------------------------------

# Function to creaate a data frame to interpretate the tt main output
# use: tt_interpretation(x), where x = main tt_test forestgeo function
# Daniel Zuleta, July 27, 2018
# load("tt_lst.rdata")


tt_interpretation <- function(ttOutput) {
  ttdf <- as.data.frame(do.call(rbind, ttOutput))

  habs <- dim(ttdf)[2] / 6 # number of habitats
  tt_interp <- data.frame() # interpretation output
  tt_interp_names <- NULL
  # j is the species loop
  # i is the habitat loop

  for (j in 1:dim(ttdf)[1]) {
    #
    for (i in 1:habs) {
      tt_interp[j, i] <- ifelse(
        ttdf[j, (i * 6) - 1] == 1 & (1 - (ttdf[j, i * 6])) < 0.05,
        "aggregated",
        ifelse(
          ttdf[j, (i * 6) - 1] == 1 &
            (1 - (ttdf[j, i * 6])) >= 0.05,
          "agg_nonsignificant",
          ifelse(
            ttdf[j, (i * 6) - 1] == -1 & (ttdf[j, i * 6]) < 0.05,
            "repelled",
            ifelse(
              ttdf[j, (i * 6) - 1] == -1 &
                (ttdf[j, i * 6]) >= 0.05,
              "rep_nonsignificant",
              "neutral"
            )
          )
        )
      )
    }
  }

  for (h in 1:habs) {
    tt_interp_names[h] <- paste("Habitat_", h, sep = "")
  }

  tt_interp <- data.frame(cbind(Species = row.names(ttdf), tt_interp))
  names(tt_interp) <- c("Species", tt_interp_names)
  return(tt_interp)
}


# Creating the input of tt_interpretation ---------------------------------

# Example from ?tt_test()

library(fgeo.habitat)
library(dplyr)

# For easier data wranging
habitat <- luquillo_habitat
census <- luquillo_top3_sp

# Pick alive trees, of 10 mm or more
pick <- filter(census, status == "A", dbh >= 10)
# Pick sufficiently abundant trees
pick <- add_count(pick, sp)
pick <- filter(pick, n > 50)

species <- unique(pick$sp)

# Test any number of species (output a list of matrices)
tt_lst <- tt_test(census, species, habitat)

tt_lst

# Using tt_interpretation -------------------------------------------------

tt_interpretation(tt_lst)

# summary -----------------------------------------------------------------

summary.tt_lst <- function(x) {
  tt_interpretation(x)
}

summary(tt_lst)
```

